---
- hosts: dotfiles
  tasks:
    - name: setup proxy for curl
      shell: echo "proxy = {{ curl_proxy }}" >~/.curlrc
      when: curl_proxy and curl_proxy | length > 0

- hosts: dotfiles
  roles:
    - role: monkeypatches
      become: true
    - git
    - zsh
    - rcm

- hosts: dotfiles
  tasks:
    - name: set git http proxy
      shell: git config --global http.proxy {{ git_http_proxy }}
      when: git_http_proxy and git_http_proxy | length > 0
    - name: set git https proxy
      shell: git config --global https.proxy {{ git_https_proxy }}
      when: git_https_proxy and git_https_proxy | length > 0

- hosts: dotfiles
  roles:
    - tmux
    - vim
    - nvim
    - role: rbenv
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.6.4
          rubies:
            - version: 2.6.4
        rbenv_users: ['{{ ansible_user_id }}']
    - role: nvm

- hosts: dotfiles
  tasks:
    - name: clone dotfiles
      git:
        repo: "https://github.com/uzxmx/dotfiles.git"
        dest: ~/.dotfiles
        accept_hostkey: true
        clone: true
        force: true
        depth: 1
    - name: run rcup
      shell: env RCRC=~/.dotfiles/rcrc rcup -f
    - name: install vim plugins
      shell: vim '+PlugInstall' '+qa'

- hosts: dotfiles
  tasks:
    - name: unset git http proxy
      shell: git config --global --unset http.proxy
      when: git_http_proxy and git_http_proxy | length > 0
    - name: unset git https proxy
      shell: git config --global --unset https.proxy
      when: git_https_proxy and git_https_proxy | length > 0

- hosts: dotfiles
  tasks:
    - name: unset proxy for curl
      shell: rm ~/.curlrc
      when: curl_proxy and curl_proxy | length > 0
