---
- hosts: dotfiles
  tasks:
    - name: setup proxy for curl
      shell: |
        echo "proxy = {{ curl_proxy }}" >~/.curlrc
        echo "proxy = {{ curl_proxy }}" | sudo tee /root/.curlrc >/dev/null
      when: curl_proxy and curl_proxy | length > 0

- hosts: dotfiles
  roles:
    - role: monkeypatches
      become: true
    - git
    - zsh
    - rcm

- hosts: dotfiles
  tasks:
    - name: set git http proxy
      shell: git config --global http.proxy {{ git_http_proxy }}
      when: git_http_proxy and git_http_proxy | length > 0
    - name: set git https proxy
      shell: git config --global https.proxy {{ git_https_proxy }}
      when: git_https_proxy and git_https_proxy | length > 0

- hosts: dotfiles
  roles:
    - tmux
    - vim
    - nvim
    - role: rbenv
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.6.4
          rubies:
            - version: 2.6.4
              env:
                # When rbenv invokes curl, it uses `-q` to disable curlrc loading, so we have to pass proxy as argument.
                RUBY_BUILD_CURL_OPTS: "{{ '--proxy ' + curl_proxy if curl_proxy and curl_proxy | length > 0 }}"
        rbenv_users: ['{{ ansible_user_id }}']
    - role: nvm

- hosts: dotfiles
  tasks:
    - name: clone or update dotfiles
      shell: |
        if $(test -d ~/.dotfiles && cd ~/.dotfiles && git status &>/dev/null); then
          cd ~/.dotfiles
          if [ -n $(git config --global --get http.proxy) ]; then
            git config http.proxy $(git config --global --get http.proxy)
            http_proxy_configured=1
          fi
          if [ -n $(git config --global --get https.proxy) ]; then
            git config https.proxy $(git config --global --get https.proxy)
            https_proxy_configured=1
          fi
          git stash
          git pull --all --recurse-submodules --rebase
          git stash pop
          if [ "$http_proxy_configured" = "1" ]; then
            git config --unset http.proxy
          fi
          if [ "$https_proxy_configured" = "1" ]; then
            git config --unset https.proxy
          fi
        else
          rm -rf ~/.dotfiles
          git clone --depth 1 --recurse-submodules https://github.com/uzxmx/dotfiles.git ~/.dotfiles
        fi
    - name: run rcup
      shell: env RCRC=$(ls -d ~)/.dotfiles/rcrc rcup -f
    - name: install vim plugins
      shell: vim '+PlugInstall' '+qa'

- hosts: dotfiles
  tasks:
    - name: unset git http proxy
      shell: git config --global --unset http.proxy
      when: git_http_proxy and git_http_proxy | length > 0
    - name: unset git https proxy
      shell: git config --global --unset https.proxy
      when: git_https_proxy and git_https_proxy | length > 0

- hosts: dotfiles
  tasks:
    - name: unset proxy for curl
      shell: |
        rm ~/.curlrc
        sudo rm /root/.curlrc
      when: curl_proxy and curl_proxy | length > 0
