---
- hosts: editor
  roles:
    - vim
    - oh-my-zsh

- hosts: editor
  tasks:
    - include_role:
        name: oh-my-zsh
    - include_role:
        name: tmux
    - include_role:
        name: rcm

    - name: Clone dotfiles
      shell: git clone --recursive https://github.com/UzxMx/dotfiles.git ~/.dotfiles
      args:
        creates: ~/.dotfiles
  
    - name: Run rcup
      shell: env RCRC=~/dotfiles/rcrc rcup -f
  
    - include_role:
        name: rbenv
  
    - name: Install vim-flavor
      shell: bash -lc 'gem install vim-flavor'
   
    - name: Run vim-flavor
      shell: bash -lc 'vim-flavor install'
      args:
        chdir: ~/.dotfiles
  
  vars:
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.5.1
      rubies:
        - version: 2.5.1
    rbenv_users: ['{{ ansible_user_id }}']
