---
- hosts: go
  roles:
    - role: go
      become: true
  vars:
    go_tarball: "go1.11.2.linux-amd64.tar.gz"
    go_tarball_checksum: "sha256:1dfe664fa3d8ad714bbd15a36627992effd150ddabd7523931f077b3926d736d"
    go_version_target: "go version go1.11.2 linux/amd64"
    go_download_location: "https://dl.google.com/go/{{ go_tarball  }}"
