---
- hosts: manager
  vars_files:
    - local_vars/kubernetes.yml
  roles:
    # - role: docker
    - role: kubernetes
      node: manager
  tags: manager

- hosts: worker
  vars_files:
    - local_vars/kubernetes.yml
  roles:
    # - role: docker
    - role: kubernetes
      node: worker
  tags: worker

- hosts: reset
  roles:
    # - role: docker
    - role: kubernetes
      operation: reset
  tags: reset

- hosts: list_kubeadm_images
  roles:
    # - role: docker
    - role: kubernetes
      operation: list_kubeadm_images
  tags: list_kubeadm_images
