- src: https://github.com/zzet/ansible-rbenv-role
  version: 3.4.1
  name: rbenv
- src: https://github.com/jlund/ansible-go
  name: go
- src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
  name: docker
- src: https://github.com/morgangraphics/ansible-role-nvm
  name: nvm
- src: https://github.com/azavea/ansible-pip
  version: 2.0.0
  name: pip
- src: https://github.com/geerlingguy/ansible-role-repo-epel
  version: 1.2.4
  name: repo-epel
- src: https://github.com/linuxhq/ansible-role-ius
  version: v0.0.8
  name: repo-ius
