- src: https://github.com/zzet/ansible-rbenv-role
  version: 3.4.1
  name: rbenv
- src: https://github.com/jlund/ansible-go
  name: go
- src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
  name: docker
