---
- shell: ssh -V 2>&1
  register: result
  ignore_errors: true

- set_fact:
    valid: "{{ result.rc == 0 and result.stdout | regex_search('^OpenSSH_([^\\s]+)', '\\1') | first >= ssh.version }}"

- name: Download ssh source
  shell: curl -C- -L -o /tmp/openssh-{{ ssh.version }}.tar.gz https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-{{ ssh.version }}.tar.gz
  when: not valid

- name: Build OpenSSH
  shell: |
    cd /tmp
    rm -rf openssh-{{ ssh.version }}
    tar zxf openssh-{{ ssh.version }}.tar.gz
    cd openssh-{{ ssh.version }} && ./configure && make
  when: not valid

- name: Install OpenSSH
  shell: cd /tmp/openssh-{{ ssh.version }} && make install
  become: true
  when: not valid

- name: Clean
  file: path={{ item }} state=absent
  with_items:
    - /tmp/openssh-{{ ssh.version }}
    - /tmp/openssh-{{ ssh.version }}.tar.gz
  when: not valid
