---
- shell: type git
  register: git_result
  ignore_errors: true

- name: Download git source
  shell: curl -o git-{{ git.version }}.tar.gz https://codeload.github.com/git/git/tar.gz/v{{ git.version }}
  args:
    chdir: /tmp
  when: git_result.rc != 0

- name: Extract git tar
  unarchive:
    src: /tmp/git-{{ git.version }}.tar.gz
    dest: /tmp
    remote_src: true
  when: git_result.rc != 0

- import_tasks: redhat.yml
  when: git_result.rc != 0 and ansible_os_family == 'RedHat'

- name: Make and install git
  shell: make configure && ./configure && make && sudo make install
  args:
    chdir: /tmp/git-{{ git.version }}
  when: git_result.rc != 0

- name: Clean
  file: path={{ item }} state=absent
  with_items:
    - /tmp/git-{{ git.version }}.tar.gz
    - /tmp/git-{{ git.version }}
  when: git_result.rc != 0
