---
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: List kubeadm images
  shell: kubeadm config images list
  register: images_result
  when: operation == 'list_kubeadm_images'

- debug:
    msg: '{{ item }}'
  loop: '{{ images_result.stdout.splitlines() }}'
  when: operation == 'list_kubeadm_images'

- name: Turn off swap
  shell: swapoff -a 
  become: true

- import_tasks: manager.yml
  when: node == 'manager' and operation == 'default'

- import_tasks: worker.yml
  when: node == 'worker' and operation == 'default'

- name: Run kubeadm reset
  shell: kubeadm reset -f && rm -rf /home/{{ ansible_user_id }}/.kube
  become: true
  when: operation == 'reset'
