---
- name: Pull kube-proxy image
  shell: |
    bash -c "
    docker pull {{ kubernetes.mirror }}/{{ item }}:{{ kubernetes.version }}
    docker tag {{ kubernetes.mirror }}/{{ item }}:{{ kubernetes.version }} k8s.gcr.io/{{ item  }}:{{ kubernetes.version }}
    "
  with_items:
    - kube-proxy
  become: true

- import_tasks: images.yml

- name: Check if worker joins a cluster
  shell: test -f /etc/kubernetes/bootstrap-kubelet.conf
  register: join_result
  ignore_errors: true

- name: Join cluster
  command: kubeadm join {{ kubernetes.kube_api_server.url }} --token {{ kubernetes.join_token }} --discovery-token-ca-cert-hash {{ kubernetes.join_discovery_token_ca_cert_hash }}
  become: true
  when: join_result.rc != 0
