---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - automake
    - build-essential
    - pkg-config
    - libevent-dev
    - libncurses5-dev
    - byacc
  become: true

- name: Remove tmux
  apt: name=tmux state=absent
  become: true
