---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - automake
    - libevent
    - libevent-devel
    - byacc
  become: true

- name: Remove tmux
  yum: name=tmux state=absent
  become: true
