---
node: 'manager'
operation: 'default'
kubernetes:
  version: v1.13.1
  mirror: mirrorgooglecontainers
  images:
    - name: mirrorgooglecontainers/pause:3.1
      tag: k8s.gcr.io/pause:3.1
    - name: mirrorgooglecontainers/etcd:3.2.24
      tag: k8s.gcr.io/etcd:3.2.24
    - name: coredns/coredns:1.2.6
      tag: k8s.gcr.io/coredns:1.2.6
    - name: fishead/quay.io.coreos.flannel:v0.10.0-amd64
      tag: quay.io/coreos/flannel:v0.10.0-amd64
  flannel_config_url: 'https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml'
  kube_api_server:
    advertise_address: ''
    url: ''
  join_token: ''
  join_discovery_token_ca_cert_hash: ''
