---
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure docker service directory present
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  become: true

- name: Copy daemon.json to docker service directory
  copy: src=daemon.json dest=/etc/systemd/system/docker.service.d/daemon.json
  become: true
  notify:
    - Reload config
    - Restart docker

- import_tasks: proxy.yml
  when: proxy == true
