---
- name: Copy http proxy conf
  template: src=http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf
  become: true
  notify:
    - Reload config
    - Restart docker

- name: Copy https proxy conf
  template: src=https-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/https-proxy.conf
  become: true
  notify:
    - Reload config
    - Restart docker
