---
- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Download nvim source
  git:
    repo: "https://github.com/neovim/neovim"
    dest: /tmp/nvim
    version: stable
    accept_hostkey: true
    clone: true
    force: true
    depth: 1

- name: Make and install nvim
  shell: make CMAKE_BUILD_TYPE=Release && make install
  args:
    chdir: /tmp/nvim
  become: true

- name: Clean
  file:
    path: /tmp/nvim
    state: absent
  become: true
