---
- shell: type nvim
  register: nvim_result
  ignore_errors: True

- import_tasks: install_from_source.yml
  when: nvim_result.rc != 0 and nvim.install_from_source

- import_tasks: install_prebuilt.yml
  when: nvim_result.rc != 0 and (not nvim.install_from_source)
