---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - ninja-build
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc-c++
    - pkgconfig
  become: true
